name: Generate terraform docs

on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Render terraform docs inside the README.md and push changes back to pushed branch
      uses: terraform-docs/gh-actions@v0.6.1
      with:
        tf_docs_working_dir: .
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'
        tf_docs_git_commit_message: 'terraform-docs: automated update action'